src/NetMVCBuilder/Models/EntityModel/MessageContact.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Data.Entity.Spatial;

namespace NetMVCBuilder.Models.EntityModel
{
    [Table("MessageContact")]
    public class MessageContact
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Email { get; set; }
        public string Message { get; set; }
        public DateTime ModifyDate { get; set; }
        public DateTime CreateDate { get; set; }
    }
}

src/NetMVCBuilder/Controllers/CategoryController.cs
using NetMVCBuilder.Common;
using NetMVCBuilder.IRepository;
using NetMVCBuilder.Models.EntityModel;
using NetMVCBuilder.Models.Enum;
using NetMVCBuilder.Models.RequestModel;
using NetMVCBuilder.Repository;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace NetMVCBuilder.Controllers
{
    public class CategoryController : BaseController
    {
        private ICategoryRepository _categoryRepository = new CategoryRepository();
        // Index
        public ActionResult Index(CategoryRequestModel model)
        {
            var currentUser = (User)Session[CommonConstants.USER_SESSION];
            model.page = model.page == 0 ? 1 : model.page;
            model.pageSize = 20;
            int totalCount = 0;

            ViewBag.hasViewPermission = CheckPermission((int)PageId.QuanLyCategory, (int)Actions.Xem, currentUser);
            ViewBag.hasAddPermission = CheckPermission((int)PageId.QuanLyCategory, (int)Actions.Them, currentUser);
            ViewBag.hasUpdatePermission = CheckPermission((int)PageId.QuanLyCategory, (int)Actions.Sua, currentUser);
            ViewBag.hasDeletePermission = CheckPermission((int)PageId.QuanLyCategory, (int)Actions.Xoa, currentUser);
            if (!ViewBag.hasViewPermission)
            {
                return RedirectToAction("NotPermission", "Home");
            }

            model.data = _categoryRepository.GetByCategory(model, model.page, model.pageSize, out totalCount);
            model.totalRecord = totalCount;
            model.totalPage = (int)Math.Ceiling((decimal)model.totalRecord / model.pageSize);
            return View(model);
        }
        // Add
        public ActionResult Add(int? id)
        {
            var checkPer = false;
            if (id == null || id <= 0){
                var currentUser = (User)Session[CommonConstants.USER_SESSION];
                checkPer = CheckPermission((int)PageId.QuanLyCategory, (int)Actions.Them, currentUser);
            }
            else{
                var currentUser = (User)Session[CommonConstants.USER_SESSION];
                checkPer = CheckPermission((int)PageId.QuanLyCategory, (int)Actions.Sua, currentUser);
                
            }
            if (checkPer == false) { return RedirectToAction("NotPermission", "Home"); }  ////check quyền
            Category rs = _categoryRepository.GetById(id);
            Category category = new Category()
            {
                Id = rs.Id,
                Name = rs.Name?.Trim(),
            };
            return View(category);
        }
        [HttpPost]
        public ActionResult AddOrUpdate(Category category)
        {
            var checkPer = false;
            if (category.Id <= 0)
            {
                var currentUser = (User)Session[CommonConstants.USER_SESSION];
                checkPer = CheckPermission((int)PageId.QuanLyCategory, (int)Actions.Them, currentUser);
            }
            else
            {
                var currentUser = (User)Session[CommonConstants.USER_SESSION];
                checkPer = CheckPermission((int)PageId.QuanLyCategory, (int)Actions.Sua, currentUser);
            }
            if (checkPer == false) { return RedirectToAction("NotPermission", "Home"); }  ////check quyền

            var result = _categoryRepository.AddOrUpdate(category);
            return Json(result == 1 ? new { status = 1, message = "Thêm thành công" } : new { status = 0, message = "Thêm thất bại" }, JsonRequestBehavior.AllowGet);
        }

        [HttpPost]
        public ActionResult CheckDuplicatedCategory(string name)
        {
            var ma = _categoryRepository.CheckDuplicatedCategory(name);
            return Json(ma == null, JsonRequestBehavior.AllowGet);
        }
    }
}

src/NetMVCBuilder/Controllers/MessageContactController.cs
using NetMVCBuilder.Common;
using NetMVCBuilder.IRepository;
using NetMVCBuilder.Models.EntityModel;
using NetMVCBuilder.Models.Enum;
using NetMVCBuilder.Models.InfoModel;
using NetMVCBuilder.Models.RequestModel;
using NetMVCBuilder.Repository;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Newtonsoft.Json;

namespace NetMVCBuilder.Controllers
{
    public class MessageContactController : BaseController
    {
        private UserRepository _userRepo = new UserRepository();

        // GET: MessageContact
        public ActionResult Index(MessageContactRequestModel model)
        {
            var currentUser = (User)Session[CommonConstants.USER_SESSION];
            model.page = model.page == 0 ? 1 : model.page;
            model.pageSize = 20;
            int totalCount = 0;
            ViewBag.hasViewPermission = CheckPermission((int)PageId.QuanLyTinNhanLienHe, (int)Actions.Xem, currentUser);
            ViewBag.hasAddPermission = CheckPermission((int)PageId.QuanLyTinNhanLienHe, (int)Actions.Them, currentUser);
            ViewBag.hasUpdatePermission = CheckPermission((int)PageId.QuanLyTinNhanLienHe, (int)Actions.Sua, currentUser);
            ViewBag.hasDeletePermission = CheckPermission((int)PageId.QuanLyTinNhanLienHe, (int)Actions.Xoa, currentUser);
            if (!ViewBag.hasViewPermission)
            {
                return RedirectToAction("NotPermission", "Home");
            }

            model.Data = _userRepo.GetMessageContact(model, model.page, model.pageSize, out totalCount);
            model.totalRecord = totalCount;
            model.totalPage = (int)Math.Ceiling((decimal)model.totalRecord / model.pageSize);
            return View(model);
        }

        [HttpGet]
        public ActionResult GetMessageContactById(int id)
        {
            var result = _userRepo.GetMessageContactById(id);
            return Json(result, JsonRequestBehavior.AllowGet);
        }

        [HttpPost]
        public ActionResult Delete(int id)
        {
            var currentUser = (User)Session[CommonConstants.USER_SESSION];
            var checkPer = CheckPermission((int)PageId.QuanLyTinNhanLienHe, (int)Actions.Xoa, currentUser);
            if (checkPer == false) { return RedirectToAction("NotPermission", "Home"); }  ////check quyền
            var result = _userRepo.DeleteMessageContact(id);
            return Json(result == 1 ? new { status = 1, message = "Xóa thành công" } : new { status = 1, message = "Xóa thất bại" }, JsonRequestBehavior.AllowGet);
        }
    }
}

src/NetMVCBuilder/Views/MessageContact/Index.cshtml
@using NetMVCBuilder.Common
@using NetMVCBuilder.Models.EntityModel
@model NetMVCBuilder.Models.RequestModel.MessageContactRequestModel
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
    var user = (User)Session[CommonConstants.USER_SESSION];
}

<head>
    <style>
        #btnSearch {
            padding: 7px 15px 7px 15px;
        }

        .lbl {
            padding: 0px;
            width: auto;
            margin-top: 8px;
            padding-left: 15px;
        }

        table {
            border: 2px solid #e8e4e4;
        }

        .paging {
            padding: 0px 15px 0px 15px;
            text-align: right;
        }

        ul {
            margin: 0px !important;
        }

        #modal_details_MessageContact {
            color: black;
        }
    </style>
</head>
<title>Quản lý tin nhắn liên hệ</title>
<body>
    <div class="container">
        <div class="table-wrapper">
            <div class="table-title">
                <div class="row">
                    <div class="col-sm-6">
                        <h2>Tìm kiếm thông tin</h2>
                    </div>
                </div>
            </div>
            <form action="@Url.Action("Index", "MessageContact")" id="search-form" method="get">
                <div class="row" style="margin-top: 20px;">
                    <div class="col-md-2"></div>
                    <label class="lbl">Từ khóa: </label>
                    <div class="col-md-6" style="margin-bottom: 10px;">
                        <input type="text" name="Keywords" placeholder="Nhập thông tin..." class="form-control" />
                    </div>
                    <div class="col-md-2">
                        <button id="btnSearch" class="btn btn-sm btn-primary filter-submit" type="submit">
                            <i class="fa fa-search"></i> Tìm kiếm
                        </button>
                    </div>
                </div>
            </form>
        </div>
    </div>

    <div class="container">
        <div class="table-wrapper">
            <div class="table-title">
                <div class="row">
                    <div class="col-sm-6">
                        <h2>Quản lý tin nhắn liên hệ</h2>
                    </div>
                    @*@if (ViewBag.hasAddPermission)
                        {
                            <div class="col-sm-6">
                                <a href="/Category/Add" class="btn btn-success" style="padding: 10px 30px 10px 30px; border-radius: 5px"><i class="fa fa-plus"></i> Thêm mới</a>
                            </div>
                        }*@
                </div>
            </div>
            <table class="table table-striped table-hover">
                <thead>
                    <tr>
                        <th class="text-center">STT</th>
                        <th class="text-center">Họ tên</th>
                        <th class="text-center">Email</th>
                        <td class="text-center">Ngày gửi</td>
                        <th class="text-center" width="300">Nội dung</th>
                        <th class="text-center" style="width:100px;">Hành động</th>
                    </tr>
                </thead>
                <tbody>
                    @{
                        var count = 0;
                    }
                    @foreach (var item in Model.Data)
                    {
                        count++;
                        <tr>
                            <td class="text-center">@count</td>
                            <td class="text-center">@item.Name</td>
                            <td class="text-center">@item.Email</td>
                            <td class="text-center">@item.CreateDate.ToString("dd/MM/yyyy")</td>
                            <td class="text-center">@item.Message</td>
                            <td class="text-center">
                                @if (ViewBag.hasViewPermission)
                                {
                                    <a class="details-link" style="margin-right: 5px; cursor: pointer" onclick="ShowDetailsMessageContact(@item.Id)"><i class="fa fa-eye" title="Xem"></i></a>
                                }
                                @if (ViewBag.hasDeletePermission)
                                {
                                    <a onclick="Delete(@item.Id)" class="delete" style="margin-right: 5px; cursor: pointer"><i class="fa fa-trash" title="Xóa"></i></a>
                                }
                            </td>
                        </tr>
                    }
                </tbody>
            </table>

            <!--Paging-->
            <div class="row paging">
                <div class="col-md-3" style="text-align: left; margin-top: 8px; padding: 0px;">
                    <label>Có tất cả @Model.totalRecord kết quả</label>
                </div>
                <div class="col-md-9" style="padding: 0px;">
                    <ul class="pagination">
                        @{
                            int position;
                            if (Model.page > 1)
                            {
                                <li class="page-item">
                                    <a class="page-link" href="@Url.Action("Index", "Category", new { page = Model.page-1, pageSize = Model.pageSize, KeySearch = Model.Keywords})" tabindex="-1"> << </a>
                                </li>
                            }

                            for (position = 1; position <= Model.totalPage; position++)
                            {

                                if (position == Model.page)
                                {
                                    <li class="page-item active"><a class="page-link" href="@Url.Action("Index", "Category", new { page = position, pageSize = Model.pageSize, KeySearch = Model.Keywords })">@position</a></li>
                                }

                                else
                                {
                                    <li class="page-item"><a class="page-link" href="@Url.Action("Index", "Category", new { page = position, pageSize = Model.pageSize, KeySearch = Model.Keywords })">@position</a></li>
                                }

                            }
                            if (Model.page > 0 && Model.page < Model.totalPage)
                            {
                                <li class="page-item">
                                    <a class="page-link" href="@Url.Action("Index", "Category", new { page = Model.page+1, pageSize = Model.pageSize, KeySearch = Model.Keywords })" tabindex="-1"> >> </a>
                                </li>
                            }

                            if (Model.totalPage == 0)
                            {
                                <li>
                                    <div role="status" aria-live="polite">Không có dữ liệu hiển thị</div>
                                </li>
                            }
                        }
                    </ul>
                </div>
            </div>
        </div>
    </div>
</body>

<script>
    function ShowDetailsMessageContact(id) {
        $.ajax({
            url: '/MessageContact/GetMessageContactById/' + id,
            type: "GET",
            success: function (rs) {
                if (rs != null && rs != undefined && rs != '') {
                    $('#modal_Name').text(rs.Name);
                    $('#modal_Email').text(rs.Email);
                    $('#modal_CreateDate').text(rs.CreateDateString);
                    $('#modal_Message').text(rs.Message);
                } else {
                    toastr.error('Có lỗi xảy ra!');
                }
            },
        });
        $('#modal_details_MessageContact').modal('show');
    }

    function Delete(id) {
        var data = {
            id: id,
        };
        var title = "Bạn có đồng ý xóa dữ liệu này không?";
        var url = '/MessageContact/Delete';
        swal({
            title: title,
            icon: "warning",
            buttons: {
                ok: "Xác nhận",
                cancel: "Hủy",
            }
        }).then((isConfirm) => {
            if (isConfirm != 'ok') {

            } else {
                $.post(url, data,
                    function (rs) {
                        if (rs.status > 0) {
                            swal({
                                title: "Xóa thành công!",
                                text: "Dữ liệu của bạn đã được cập nhật!",
                                icon: "success",
                            }).then(function (isConfirm) {
                                window.location.href = '/MessageContact';
                            });
                        }
                        else {
                            toastr.error(rs.message);
                        }
                    });
            }
        });
    }
</script>