src/NetMVCBuilder/Models/EntityModel/ProductDetail.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;

namespace NetMVCBuilder.Models.EntityModel
{
    [Table("ProductDetail")]
    public class ProductDetail
    {
        public int Id { get; set; }
        public int? ProductId { get; set; }
        public int? SizeId { get; set; }
        public int? Quantity { get; set; }// số lượng nhập từ trước đến giờ
        public int? QuantityCurrent { get; set; }// số lượng hiện tại trong kho
        public int? QuantityLimit { get; set; }// Giới hạn số lượng báo động hết hàng
        public int? ColorId { get; set; }
        public decimal? Price { get; set; } // giá nhập của sản phẩm
        public DateTime? CreatedDate { get; set; }
        public DateTime? ModifiedDate { get; set; }
    }
}

src/NetMVCBuilder/Controllers/ListProductsController.cs
using System.Web.Mvc;
using NetMVCBuilder.Repository;
using NetMVCBuilder.Models.RequestModel;

namespace NetMVCBuilder.Controllers
{
    public class ListProductsController : Controller
    {
        private ProductRepository _sanPhamRepository = new ProductRepository();
        private CategoryRepository categoryRepository = new CategoryRepository();
        private ContactRepository _contactRepo = new ContactRepository();

        // GET: ListProducts
        public ActionResult Index(string KeySearch, int? categoryId, int page = 1, int pageSize = 12)
        {
            ProductRequestModel model = _sanPhamRepository.GetBySanPham(KeySearch, categoryId, page, pageSize);
            
            ViewBag.listCategory = categoryRepository.GetAll().ToArray();
            ViewBag.categoryId = categoryId;

            return View(model);
        }

        [Route("{id: int}")]
        public ActionResult ProductDetail(int id)
        {
            Models.InfoModel.ProductInfo model = _sanPhamRepository.GetById(id);
            ViewBag.PhoneNumber = _contactRepo.GetInfo().PhoneNumber;
            return View(model);
        }

        [HttpGet]
        public ActionResult GetListProducts(string KeySearch, int? categoryId, int page = 1, int pageSize = 12)
        {
            ProductRequestModel model = _sanPhamRepository.GetBySanPham(KeySearch, categoryId, page, pageSize);
            return Json(model, JsonRequestBehavior.AllowGet);
        }
    }
}

src/NetMVCBuilder/Views/ListProducts/Index.cshtml
@model NetMVCBuilder.Models.RequestModel.ProductRequestModel

@{
    ViewBag.Title = "Các sản phẩm";
    Layout = "~/Views/Shared/HomeLayout.cshtml";
}
<style>
    body {
        background: #ebebeb;
    }

    .pix_section {
        background-color: white;
    }

    .footer-container {
        background: white;
    }
</style>

<style>
    .no-content {
        display: flex;
        justify-content: center;
        align-items: center;
        width: 100%;
        min-height: 150px;
    }

    @@media screen and (min-height: 700px) {
        .no-content {
            min-height: 250px;
        }
    }

    @@media screen and (min-height: 900px) {
        .no-content {
            min-height: 350px;
        }
    }
</style>

<style>
    .product-container {
        background-size: cover;
        background-position: center;
    }

        .product-container img {
            width: 100%;
            cursor: pointer;
            transition: all linear .2s;
        }

    .product-img:hover {
        transform: scale(1.08, 1.08);
    }

    .product-name {
        text-transform: uppercase;
        cursor: pointer;
    }

        .product-name:hover {
            color: #1964B9;
        }

    .product-type-tag {
        display: inline-block;
        padding: 5px 9px;
        border-bottom: 3px solid white;
        min-width: 100px;
        text-align: center;
        margin: 4px;
    }


        .product-type-tag:hover {
            border-bottom: 3px solid #1964B9;
            cursor: pointer;
        }

            .product-type-tag:hover a {
                color: #1964B9;
            }

        .product-type-tag.activate {
            border-bottom: 3px solid #1964B9;
        }

    .container.white-bg {
        border-radius: 10px
    }

    .product-container {
        display: inline-block;
        position: relative;
        width: 100%;
    }

        .product-container:before {
            content: "";
            display: block;
            margin-top: 100%;
        }

    .product-img {
        width: 100%;
        height: 100%;
    }

    .element {
        position: absolute;
        top: 0;
        bottom: 0;
        left: 0;
        right: 0;
        background-color: silver /* show me! */
    }
</style>

<script>
    $(".product-type-tag").on("click", function () {
        $(".product-img-parent").attr('src', $(this).attr('src'));
        $(".product-img-child.active").removeClass('active');
        $(this).addClass("active");
    });
</script>

@*<script>
        function getListProducts(page, pageSize, key, categoryId) {
            $("#loading-icon").css("display", "flex");
            $.ajax({
                url: '/ListProducts/GetListProducts/',
                method: 'GET',
                data: {
                    page: page,
                    pageSize: pageSize,
                    KeyWord: key,
                    categoryId: categoryId
                },
                dataType: 'json',
                contentType: 'application/json; charset=utf-8',
                success: function (res) {
                    if (res.data) {
                        $("#list-products-container").empty();
                        for (var item of res.data) {
                            var product =
                                `<div class="col-md-3 col-sm-6 col-xs-6">
                                <div class="pix-content pix-margin-v-10 text-center">
                                    <div class="product-container">
                                        <img src="https://giaysihcm.com/wp-content/uploads/2021/04/z2468147045197_8719efcb5296ac77b24a2bcd778da748-scaled.jpg" alt="" class="product-img" onclick='window.location.href="/ListProducts/ProductDetail/${item.Id}"'>
                                    </div>
                                    <h6 class="pix-black-gray-dark pix-no-margin-bottom pix-padding-v-10">
                                        <span class="pix_edit_text" style="text-transform: uppercase;">${item.Name}</span>
                                    </h6>
                                </div>
                            </div>`;

                            $("#list-products-container").append(product);
                        }
                    }
                    $("#loading-icon").css("display", "none");
                },
                error: function (xhr) {
                    console.log(xhr);
                    $("#loading-icon").css("display", "none");
                }
            })
        }
    </script>*@

<div class="pix-padding-v-content">
    <div class="container white-bg">
        <div class="row" style="padding: 20px 10px">
            <div class="@(ViewBag.categoryId == null ? "product-type-tag activate": "product-type-tag")"
                 onclick='window.location.href = "@Url.Action("Index", "ListProducts")"'>
                <span>Tất cả sản phẩm</span>
            </div>
            @{
                foreach (var item in ViewBag.listCategory)
                {
                    <div class="@(ViewBag.categoryId == item.Id ? "product-type-tag activate" : "product-type-tag")"
                         onclick='window.location.href = "@Url.Action("Index", "ListProducts", new {categoryId = item.Id})"'>
                        <span>@item.Name</span>
                    </div>
                }
            }
        </div>
        @*<div id="loading-icon" class="row" style="display: flex; justify-content: center; align-items: center; min-height: 150px;">
                <div class="lds-dual-ring">
                </div>
            </div>*@
        <div class="row">
            <div id="list-products-container" class="col-xs-12">
                @{
                    foreach (var item in Model.data)
                    {
                        <div class="col-md-3 col-sm-6 col-xs-6">
                            <div class="pix-content pix-margin-v-10 text-center">
                                <div class="product-container">
                                    <div class="element">
                                        <img src="@(item.PictureThumbnail?.Trim())" alt="" class="product-img" onclick='window.location.href="/ListProducts/ProductDetail/@item.Id"'>
                                    </div>
                                </div>
                                <h6 class="pix-black-gray-dark pix-no-margin-bottom pix-padding-v-10">
                                    <span class="pix_edit_text product-name" onclick='window.location.href="/ListProducts/ProductDetail/@item.Id"'>@item.Name</span>
                                </h6>
                            </div>
                        </div>
                    }
                }
            </div>
        </div>
        @if (Model.totalPage != 0)
        {
            <div class="col-xs-12 pix-margin-v-10" style="display: flex; justify-content: end">
                <ul class="pagination">
                    @{
                        int position;
                        if (Model.page > 1)
                        {
                            <li class="page-item">
                                <a class="page-link" href="@Url.Action("Index", "ListProducts", new { page = Model.page - 1, pageSize = Model.pageSize, KeySearch = Model.Keywords })" tabindex="-1"> Trước </a>
                            </li>
                        }

                        for (position = 1; position <= Model.totalPage; position++)
                        {

                            if (position == Model.page)
                            {
                                <li class="page-item active"><a class="page-link" href="@Url.Action("Index", "ListProducts", new { page = position, pageSize = Model.pageSize, KeySearch = Model.Keywords })">@position</a></li>
                            }

                            else
                            {
                                <li class="page-item"><a class="page-link" href="@Url.Action("Index", "ListProducts", new { page = position, pageSize = Model.pageSize, KeySearch = Model.Keywords })">@position</a></li>
                            }

                        }
                        if (Model.page > 0 && Model.page < Model.totalPage)
                        {
                            <li class="page-item">
                                <a class="page-link" href="@Url.Action("Index", "ListProducts", new { page = Model.page + 1, pageSize = Model.pageSize, KeySearch = Model.Keywords })" tabindex="-1"> Sau </a>
                            </li>
                        }

                    }
                </ul>
            </div>


        }
        @if (Model.totalPage == 0)
        {
            <div class="no-content">
                <span>Không có dữ liệu hiển thị</span>
            </div>
        }
    </div>
</div>

src/NetMVCBuilder/Views/ListProducts/ProductDetail.cshtml
@model NetMVCBuilder.Models.InfoModel.ProductInfo

@{
    ViewBag.Title = "Chi tiết sản phẩm";
    Layout = "~/Views/Shared/HomeLayout.cshtml";
}

<style>
    body {
        background: #ebebeb;
    }

    .pix_section {
        background-color: white;
    }

    .footer-container {
        background: white;
    }
</style>


<style>
    .product-name {
        text-transform: uppercase;
        cursor: pointer;
    }

        .product-name:hover {
            color: #1964B9;
        }

    .product-img-parent {
        border-radius: 15px;
        width: 100%;
    }

    .product-list-img-child {
        display: flex;
        flex-direction: column;
    }

    .product-img-child {
        width: 50px;
        height: 50px;
        margin-bottom: 10px;
        border-radius: 5px;
        cursor: pointer;
    }

        .product-img-child.active {
            border: 2px solid #ff5000;
        }

        .product-img-child:hover {
            border: 2px solid #ff5000;
        }
</style>
<style>
    .product-container {
        background-size: cover;
        background-position: center;
    }

        .product-container img {
            width: 100%;
            cursor: pointer;
            transition: all linear .2s;
        }

    .product-img:hover {
        transform: scale(1.08, 1.08);
    }

    .breadcrumb {
        padding: 12px;
        color: blue;
        margin: 15px;
        background: none;
    }

    .text-muted {
        color: #337ab7;
    }

    .breadcrumb > li + li:before {
        padding: 0;
    }
</style>

<div class="pix-padding-v-content">
    <div class="container">
        <div class="row">
            <div class="col-md-12 col-xs-12">
                <div class="row">
                    <div class="card card-custom gutter-b example example-compact">
                        <div class="card-header">
                            <h3 class="card-title">Chi tiết sản phẩm</h3>
                            <ul class="breadcrumb breadcrumb-transparent breadcrumb-dot font-weight-bold">
                                <li class="breadcrumb-item text-muted">
                                    <a href="/" class="text-muted">Trang chủ</a>
                                </li>
                                <li class="breadcrumb-item text-muted">
                                    <a href="/ListProducts?categoryId=@Model.CategoryId" class="text-muted">@Model.CategoryName</a>
                                </li>
                            </ul>
                        </div>
                        <div class="card-body">
                            <div class="col-sm-6 col-xs-12">
                                <div class="col-xs-10" style="padding-left: 0px">
                                    <img class="product-img-parent" src="@Model.PictureThumbnail" />
                                </div>
                                <div class="col-xs-2 product-list-img-child" style="padding-left: 0px">
                                    @foreach (var item in Model.ListImage)
                                    {
                                        <img class="product-img-child @(item.ImagePath?.Trim() == Model.PictureThumbnail?.Trim() ? "active" : "")" src="@(item.ImagePath?.Trim())" />
                                    }
                                </div>
                            </div>
                            <div class="col-sm-6 col-xs-12">
                                <div class="row form-group">
                                    <div class="col-xs-12">
                                        <h4 class="text-primary m-0">@Model.Name</h4>
                                    </div>
                                </div>
                                <div class="row form-group">
                                    <div class="col-xs-4">
                                        <span class="col-form-label">Thương hiệu: </span>
                                    </div>
                                    <div class="col-xs-8">
                                        <span class="col-form-label">ThanhPhatShoes</span>
                                    </div>
                                </div>
                                <div class="row form-group">
                                    <div class="col-xs-4">
                                        <span class="col-form-label">Mã SP: </span>
                                    </div>
                                    <div class="col-xs-8">
                                        <span class="col-form-label">@Model.Code</span>
                                    </div>
                                </div>

                                <div class="row form-group">
                                    <div class="col-xs-4">
                                        <span class="col-form-label">Màu sắc: </span>
                                    </div>
                                    <div class="col-xs-8">
                                        <span class="col-form-label">@Model.lstColor</span>
                                    </div>
                                </div>
                                <div class="row form-group">
                                    <div class="col-xs-4">
                                        <span class="col-form-label">Kích thước: </span>
                                    </div>
                                    <div class="col-xs-8">
                                        <span class="col-form-label">@Model.lstSize</span>
                                    </div>
                                </div>
                                <div class="row">
                                    <div class="col-xs-12">
                                        <hr />
                                    </div>
                                </div>
                                <div class="row">
                                    <div class="col-xs-12">
                                        <div style="display: flex; justify-content: center;">
                                            <div class="phone-container" onclick="window.open('tel:0384593636');">
                                                <i class="fas fa-phone-alt" style="color: white"></i>
                                                <span class="pix_edit_text pix-white"><strong>Liên hệ ngay: @ViewBag.PhoneNumber</strong></span>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>

                            <div class="col-xs-12" style="margin-top: 30px">
                                <h6>Mô tả chi tiết</h6>
                                <hr />
                                <div>
                                    @Html.Raw(Model.Description)
                                </div>
                            </div>

                            <div class="col-xs-12" style="margin-top: 30px">
                                <h6>Sản phẩm tương tự</h6>
                                <hr />
                                @if (Model.ListSameProduct.Count > 0)
                                {
                                    foreach (var item in Model.ListSameProduct)
                                    {
                                        <div class="col-md-3 col-sm-4 col-xs-6">
                                            <div class="pix-content pix-margin-v-10 text-center">
                                                <div class="product-container">
                                                    <img src="@(item.PictureThumbnail?.Trim())"
                                                         alt="" class="product-img"
                                                         style="width: 100%"
                                                         onclick='window.location.href = "@Url.Action("productdetail", "listproducts", new { id = item.Id})"'>
                                                </div>
                                                <h6 class="pix-black-gray-dark pix-no-margin-bottom pix-padding-v-10">
                                                    <span class="pix_edit_text product-name"
                                                          onclick='window.location.href = "@Url.Action("productdetail", "listproducts", new { id = item.Id})"'>@item.Name</span>
                                                    </h6>
                                                </div>
                                            </div>
                                        }
                                    }
                                    else
                                    {
                                        <div style="display: flex; justify-content: center; align-items: center; width: 100%; min-height: 150px">
                                            <span>Không có dữ liệu hiển thị</span>
                                        </div>
                                    }

                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<style>
    .phone-container {
        background-color: orangered;
        border-radius: 25px;
        padding: 10px 20px;
        cursor: pointer;
    }
</style>
<script>
    $(".product-img-child").on("click", function () {
        $(".product-img-parent").attr('src', $(this).attr('src'));
        $(".product-img-child.active").removeClass('active');
        $(this).addClass("active");
    });
</script>