src/NetMVCBuilder/Controllers/FileController.cs
using Namek.Core.Utility;
using NetMVCBuilder.Common;
using NetMVCBuilder.IRepository;
using NetMVCBuilder.Models.EntityModel;
using NetMVCBuilder.Models.RequestModel;
using NetMVCBuilder.Repository;
using System;
using System.Collections.Generic;
using System.Drawing;
using System.IO;
using System.Linq;
using System.Text;
using System.Web;
using System.Web.Mvc;

namespace NetMVCBuilder.Controllers
{
    public class FileController : Controller
    {
        private static INewsArticleRepository _news = new NewsArticleRepository();

        [HttpPost]
        [ActionName("Files")]
        public JsonResult Files(MediaSelectorSearchQuery mediaCategory)
        {
            var currentUser = (User)Session[CommonConstants.USER_SESSION];
            List<ProductImage> lst = new List<ProductImage>();
            foreach (string files in Request.Files)
            {
                var file1 = Request.Files[files];
                var stream = file1.InputStream;
                var FileName = file1.FileName.Replace(" ", "-"); // file name hiển thị cho người dùng

                string fileLocation = Server.MapPath("~/Images/ImageNews");
                if (!Directory.Exists(fileLocation)) { Directory.CreateDirectory(fileLocation); }

                var fileId = Guid.NewGuid().ToString(); //file name định danh lưu ở db và thư mục
                if (!Utils.CheckFileExtension(file1.FileName, out var extension))
                    throw new InvalidDataException($"File extension is denied.");

                System.Drawing.Image image = System.Drawing.Image.FromStream(stream);
                byte[] byteImg = Utils.convertImagetoByte(image);

                var fileName = Path.GetFileName(fileId) + $".{extension}";
                var file = Path.Combine(fileLocation, Path.GetFileName(fileId)) + $".{extension}";
                System.IO.File.WriteAllBytes(file, byteImg);
                
                ProductImage img = new ProductImage()
                {
                    ImagePath = "/Images/ImageNews/" + fileName,
                    NameDisplay = FileName,
                    ContentLength = stream.Length.ToString(),
                    CreatedBy = currentUser.id,
                    CreatedDate = DateTime.Now,
                    ModifiedDate = DateTime.Now,
                    ModifiedBy = currentUser.id,
                };
                lst.Add(img);
                stream.Dispose();
            }
            if (lst.Count > 0)
            {
                var rs = _news.AddImage(lst);
                return Json(rs, "text/html", Encoding.UTF8);
            }
            return Json(null, "text/html", Encoding.UTF8);
        }

    }
}

src/NetMVCBuilder/Controllers/MediaSelectorController.cs
using Namek.Core.Utility;
using NetMVCBuilder.AttributeCustom;
using NetMVCBuilder.IRepository;
using NetMVCBuilder.Models.EntityModel;
using NetMVCBuilder.Models.RequestModel;
using NetMVCBuilder.Repository;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace NetMVCBuilder.Controllers
{
    public class MediaSelectorController : BaseController
    {
        private static IMediaRepository _med = new MediaRepository();
        private static INewsArticleRepository _news = new NewsArticleRepository();
        public MediaSelectorController()
        {

        }
        [XFrameOptionsFilterAttribute]
        public ActionResult Show(MediaSelectorSearchQuery Query)
        {
            if (Query == null)
            {
                Query = new MediaSelectorSearchQuery();
                string request = Request["Query"];
                Query.Query = request;
            }
            Query.page = Query.page == 0 ? 1 : Query.page;
            Query.pageSize = 100;
            int totalCount = 0;
            Query.data = _med.Search(Query, Query.page, Query.pageSize, out totalCount);
            Query.totalRecord = totalCount;
            Query.totalPage = (int)Math.Ceiling((decimal)Query.totalRecord / Query.pageSize);

            return PartialView("Show", Query);
        }

        public JsonResult GetFileInfo(string value)
        {
            var mediafile = _med.GetById(value);

            var SelectedItemInfo = new
            {
                Url = mediafile.ImagePath?.Trim(),
            };
            return Json(SelectedItemInfo, JsonRequestBehavior.AllowGet);
        }

        public JsonResult GetImageData(string url)
        {
            string decodedUrl = Utils.DecodeUrlString(url);

            ProductImage image = _med.GetByUrl(decodedUrl);

            return Json(new { alt = image.NameDisplay?.Trim(), title = image.NameDisplay?.Trim(), url = image.ImagePath?.Trim() }, JsonRequestBehavior.AllowGet);
        }
    }
}

src/NetMVCBuilder/Views/MediaSelector/FileResult.cshtml
@using System.Drawing
@model NetMVCBuilder.Models.EntityModel.ProductImage
@{
    Layout = "";

}
<div class="file-result" data-file-result="@Model.Id">
    <div class="header">
        <div class="row">
            <div class="col-md-2">
                <img class="img-responsive" id="" style="max-width: 120px;max-height:63px; margin-bottom: 5px;" src="@Model.ImagePath" />
            </div>
            <div class="col-md-10">
                @Model.NameDisplay - @(Model.ContentLength ?? "0") bytes
                &emsp;
                <input type="button" class="btn-primary btn btn-sm" data-file="@Model.Id" id="test_@Model.Id" data-action="select" value="Chọn file" />
            </div>
        </div>
    </div>
</div>

src/NetMVCBuilder/Views/MediaSelector/Show.cshtml
@using System.Collections.Generic
@using System.Linq
@using NetMVCBuilder.Models.EntityModel
@model NetMVCBuilder.Models.RequestModel.MediaSelectorSearchQuery

<link href="~/Content/mrcms/Styles/jquery.mrcms-mediaselector.css" rel="stylesheet" />
<link href="~/Content/mrcms/Styles/featherlight.css" rel="stylesheet" />
<link href="~/Content/mrcms/Styles/jquery.tagit.css" rel="stylesheet" />
<link href="~/Content/mrcms/Styles/jquery-ui-bootstrap/jquery-ui-1.9.2.custom.css" rel="stylesheet" />
<link href="~/Content/mrcms/Scripts/lib/jstree/themes/default/style.css" rel="stylesheet" />
<link href="~/Content/mrcms/Styles/bootstrap/css/bootstrap.css" rel="stylesheet" />
<link href="~/Content/mrcms/Styles/bootstrap/css/bootstrap-theme.css" rel="stylesheet" />
<link href="~/Content/mrcms/Styles/dropzone.css" rel="stylesheet" />
<link href="~/Content/mrcms/Styles/mrcms-admin.css" rel="stylesheet" />

<div class="modal-body" data-type="media-selector-popup" style="min-height: 250px;width: 99% !important;height: 99% !important; overflow:auto">
    <div class="row">
        @using (Html.BeginForm("Show", "MediaSelector", FormMethod.Get, new { id = "search-form", @class = "form-inline" }))
        {
            <fieldset>
                <div class="form-group" style="padding-left: 15px;">
                    <div class="row" style="padding-left: 15px;">
                        <h2>Lựa chọn hình ảnh</h2>
                    </div>

                    <div class="row" style="padding-left: 15px;">
                        <div class="form-group">
                            @Html.TextBoxFor(query => query.Query, new { @class = "form-control", @placeholder = "Tìm kiếm ảnh" })
                        </div>
                        <input type="submit" class="btn btn-primary" value="Tìm kiếm" />
                    </div>
                </div>
            </fieldset>
        }
    </div>
    <div id="results">
        <div id="fileupload" data-message="Click vào đây hoặc kéo thả để tải ảnh lên" class="dropzone margin-bottom-10 margin-top-10"></div>
        <input type="hidden" value="@Url.Action("Files", "File", new { Id = (Model.Id ?? null) })" id="action-url" />

        <div id="progress" class="progress" style="height: 30px; display: none; margin-bottom: 5px;">
            <div class="bar"><span id="percent-complete" style="text-align: center;"></span></div>
        </div>
        <div id="files" class=""></div>

        <input type="hidden" id="allowedFileTypes" value=".gif,.jpeg,.jpg,.png,.svg,.tif,.tiff,.bmp" />
        <input type="hidden" id="maxFileSizeUpload" value="10000000" />

        @if (Model.data.Count > 0)
        {
            <div class="row" style="padding-left:15px;padding-bottom: 15px;">
                @foreach (var file in Model.data)
                {
                    Html.RenderPartial("FileResult", file);
                }
            </div>
            <div class="clearfix"></div>
        }
        else
        {
            <p>Không có ảnh nào ở đây - bạn hãy thử upload 1 ảnh!</p>
        }
    </div>
</div>